kind = "DojoContract"
class_hash = "0x27fa0d39964487211324e94f5fd3a876d30a699a1ad749247b5f500be1ea3cd"
original_class_hash = "0x27fa0d39964487211324e94f5fd3a876d30a699a1ad749247b5f500be1ea3cd"
base_class_hash = "0x0"
abi = "manifests/mainnet/base/abis/contracts/octoguns-actions-3f08332a.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-actions"
systems = ["move"]
manifest_name = "octoguns-actions-3f08332a"
