[world]
kind = "WorldContract"
class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
original_class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
abi = "manifests/slot/deployment/abis/dojo-world.json"
address = "0x6715946eb3900f0be7dc465125c194280fdca727bf3071972dcda5ad9a612c8"
transaction_hash = "0x41c85498d1bed4eb3fc4ec304f4a5158f79c2e1648d15428070699d35afdc2f"
block_number = 3
seed = "octoguns"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "slot"
rpc_url = "https://api.cartridge.gg/x/octoguns-alpha2/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slot/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x5f4dde0e6c7a19c9695ba9c7d40b41e4c4b93e8da2d77561859f1bd19468670"
class_hash = "0x18605b41332326f7bded1b1f3f668a7d81850b01bbd77bd369e3efe0408aa8e"
original_class_hash = "0x18605b41332326f7bded1b1f3f668a7d81850b01bbd77bd369e3efe0408aa8e"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slot/deployment/abis/contracts/octoguns-actions-3f08332a.json"
reads = []
writes = [
    "octoguns-CharacterPosition",
    "octoguns-CharacterModel",
    "octoguns-Map",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-TurnData",
]
init_calldata = []
tag = "octoguns-actions"
systems = ["move"]
manifest_name = "octoguns-actions-3f08332a"

[[contracts]]
kind = "DojoContract"
address = "0x227f9725f6aaefe0189e5457b0cbfb52d77e13687b0af6586ba932ad66d8d84"
class_hash = "0x1352d5ee66110af2b5911271b20854296a5ecbd5e538cee1ff53d51f14f2ffe"
original_class_hash = "0x1352d5ee66110af2b5911271b20854296a5ecbd5e538cee1ff53d51f14f2ffe"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slot/deployment/abis/contracts/octoguns-mapmaker-14c58c7d.json"
reads = []
writes = [
    "octoguns-CharacterPosition",
    "octoguns-CharacterModel",
    "octoguns-Map",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-Global",
]
init_calldata = []
tag = "octoguns-mapmaker"
systems = [
    "default_map",
    "create",
]
manifest_name = "octoguns-mapmaker-14c58c7d"

[[contracts]]
kind = "DojoContract"
address = "0x2202c337a1ce21f8c50675ca23fad33bd0d8d88d8c6b78615ffbe6abee67a28"
class_hash = "0x31a4d9c145241708d41b4699e0e70da082ef5a29f7c17ab66056ddef6707b54"
original_class_hash = "0x31a4d9c145241708d41b4699e0e70da082ef5a29f7c17ab66056ddef6707b54"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slot/deployment/abis/contracts/octoguns-spawn-1acb0980.json"
reads = []
writes = [
    "octoguns-CharacterPosition",
    "octoguns-CharacterModel",
    "octoguns-Map",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-Player",
]
init_calldata = []
tag = "octoguns-spawn"
systems = ["spawn"]
manifest_name = "octoguns-spawn-1acb0980"

[[contracts]]
kind = "DojoContract"
address = "0x62fcf9f93982a5f41a9c515149d454a44750a68089d6baf8196052dd1bbc161"
class_hash = "0x18d7f3422a7d8b32eeb46b112b0931f13e86e5649a75548a9bfa2e4d1289243"
original_class_hash = "0x18d7f3422a7d8b32eeb46b112b0931f13e86e5649a75548a9bfa2e4d1289243"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slot/deployment/abis/contracts/octoguns-start-5506b80f.json"
reads = []
writes = [
    "octoguns-CharacterPosition",
    "octoguns-CharacterModel",
    "octoguns-Map",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-Global",
    "octoguns-Player",
    "octoguns-SessionPrimitives",
]
init_calldata = []
tag = "octoguns-start"
systems = [
    "create_closed",
    "join",
]
manifest_name = "octoguns-start-5506b80f"

[[models]]
kind = "DojoModel"
class_hash = "0x5e0d858c19586c631802aa462ab7cb204912efe0d8f468305054d0db1344cb7"
original_class_hash = "0x5e0d858c19586c631802aa462ab7cb204912efe0d8f468305054d0db1344cb7"
abi = "manifests/slot/deployment/abis/models/octoguns-Bullet-69e7a9ab.json"
tag = "octoguns-Bullet"
qualified_path = "octoguns::models::bullet::bullet"
manifest_name = "octoguns-Bullet-69e7a9ab"

[[models.members]]
name = "bullet_id"
type = "u32"
key = true

[[models.members]]
name = "shot_step"
type = "u16"
key = false

[[models.members]]
name = "shot_by"
type = "u32"
key = false

[[models.members]]
name = "shot_at"
type = "Vec2"
key = false

[[models.members]]
name = "velocity"
type = "IVec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x660f2f126db3f73a49645f5a1db074be8c3dafc090bc0afe81cefa4d10b7f3d"
original_class_hash = "0x660f2f126db3f73a49645f5a1db074be8c3dafc090bc0afe81cefa4d10b7f3d"
abi = "manifests/slot/deployment/abis/models/octoguns-CharacterModel-66c7439d.json"
tag = "octoguns-CharacterModel"
qualified_path = "octoguns::models::characters::character_model"
manifest_name = "octoguns-CharacterModel-66c7439d"

[[models.members]]
name = "entity_id"
type = "u32"
key = true

[[models.members]]
name = "session_id"
type = "u32"
key = false

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = false

[[models.members]]
name = "steps_amount"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x67e24ab3c6231d59ebfa89355dc6723dd98f47baf73c048e9f64791c9e26e59"
original_class_hash = "0x67e24ab3c6231d59ebfa89355dc6723dd98f47baf73c048e9f64791c9e26e59"
abi = "manifests/slot/deployment/abis/models/octoguns-CharacterPosition-66fdf8ab.json"
tag = "octoguns-CharacterPosition"
qualified_path = "octoguns::models::characters::character_position"
manifest_name = "octoguns-CharacterPosition-66fdf8ab"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "coords"
type = "Vec2"
key = false

[[models.members]]
name = "max_steps"
type = "u32"
key = false

[[models.members]]
name = "current_step"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x26c0fcbfc402b24c8481866784bc2edbbaa7321ec12cb435fca258f76fea25"
original_class_hash = "0x26c0fcbfc402b24c8481866784bc2edbbaa7321ec12cb435fca258f76fea25"
abi = "manifests/slot/deployment/abis/models/octoguns-Global-23c9ff90.json"
tag = "octoguns-Global"
qualified_path = "octoguns::models::global::global"
manifest_name = "octoguns-Global-23c9ff90"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "pending_sessions"
type = "Array<u32>"
key = false

[[models.members]]
name = "map_count"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6f5dd520b74682ba2ec25cc02f73b38064c58d272e585a250c2edebdcb13f22"
original_class_hash = "0x6f5dd520b74682ba2ec25cc02f73b38064c58d272e585a250c2edebdcb13f22"
abi = "manifests/slot/deployment/abis/models/octoguns-Map-6508b277.json"
tag = "octoguns-Map"
qualified_path = "octoguns::models::map::map"
manifest_name = "octoguns-Map-6508b277"

[[models.members]]
name = "map_id"
type = "u32"
key = true

[[models.members]]
name = "grid1"
type = "u256"
key = false

[[models.members]]
name = "grid2"
type = "u256"
key = false

[[models.members]]
name = "grid3"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x40b4e50b38be60baa3ab53f71331d733346d71048f0835abebe0219ee00313"
original_class_hash = "0x40b4e50b38be60baa3ab53f71331d733346d71048f0835abebe0219ee00313"
abi = "manifests/slot/deployment/abis/models/octoguns-Player-5a4c6c7b.json"
tag = "octoguns-Player"
qualified_path = "octoguns::models::player::player"
manifest_name = "octoguns-Player-5a4c6c7b"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "games"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3fc1d9de1c4b38b0e29db41d9c3b9bc32276aafc0088c21f4d92b4bd9f3e49d"
original_class_hash = "0x3fc1d9de1c4b38b0e29db41d9c3b9bc32276aafc0088c21f4d92b4bd9f3e49d"
abi = "manifests/slot/deployment/abis/models/octoguns-Session-41d1f2ce.json"
tag = "octoguns-Session"
qualified_path = "octoguns::models::sessions::session"
manifest_name = "octoguns-Session-41d1f2ce"

[[models.members]]
name = "session_id"
type = "u32"
key = true

[[models.members]]
name = "player1"
type = "ContractAddress"
key = false

[[models.members]]
name = "player2"
type = "ContractAddress"
key = false

[[models.members]]
name = "map_id"
type = "u32"
key = false

[[models.members]]
name = "state"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x28f28d0f03544299f5be80803fd6c00c5226857cfb2580d4f5de12ccc4aab82"
original_class_hash = "0x28f28d0f03544299f5be80803fd6c00c5226857cfb2580d4f5de12ccc4aab82"
abi = "manifests/slot/deployment/abis/models/octoguns-SessionMeta-4f7fd982.json"
tag = "octoguns-SessionMeta"
qualified_path = "octoguns::models::sessions::session_meta"
manifest_name = "octoguns-SessionMeta-4f7fd982"

[[models.members]]
name = "session_id"
type = "u32"
key = true

[[models.members]]
name = "turn_count"
type = "u32"
key = false

[[models.members]]
name = "p1_character"
type = "u32"
key = false

[[models.members]]
name = "p2_character"
type = "u32"
key = false

[[models.members]]
name = "bullets"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x557c8f93ab95b683d7a467f9838893a63a782bd65a4d747a96ad2630c9789cd"
original_class_hash = "0x557c8f93ab95b683d7a467f9838893a63a782bd65a4d747a96ad2630c9789cd"
abi = "manifests/slot/deployment/abis/models/octoguns-SessionPrimitives-29e33ecc.json"
tag = "octoguns-SessionPrimitives"
qualified_path = "octoguns::models::sessions::session_primitives"
manifest_name = "octoguns-SessionPrimitives-29e33ecc"

[[models.members]]
name = "session_id"
type = "u32"
key = true

[[models.members]]
name = "bullet_speed"
type = "u64"
key = false

[[models.members]]
name = "bullet_sub_steps"
type = "u32"
key = false

[[models.members]]
name = "bullets_per_turn"
type = "u32"
key = false

[[models.members]]
name = "sub_moves_per_turn"
type = "u32"
key = false

[[models.members]]
name = "max_distance_per_sub_move"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x28ec07b8933b445f9dcc40ec316b0636b59c869fd2dc62de8d58166e83fb057"
original_class_hash = "0x28ec07b8933b445f9dcc40ec316b0636b59c869fd2dc62de8d58166e83fb057"
abi = "manifests/slot/deployment/abis/models/octoguns-TurnData-293d224e.json"
tag = "octoguns-TurnData"
qualified_path = "octoguns::models::turndata::turn_data"
manifest_name = "octoguns-TurnData-293d224e"

[[models.members]]
name = "session_id"
type = "u32"
key = true

[[models.members]]
name = "turn_number"
type = "u32"
key = true

[[models.members]]
name = "moves"
type = "TurnMove"
key = false
