kind = "DojoContract"
class_hash = "0x5a48daad96a4b76834fb6f09fe0cf214a78e95ab9757e76633ffc3097b53570"
original_class_hash = "0x5a48daad96a4b76834fb6f09fe0cf214a78e95ab9757e76633ffc3097b53570"
base_class_hash = "0x0"
abi = "manifests/mainnet/base/abis/contracts/octoguns-actions-3f08332a.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-actions"
systems = ["move"]
manifest_name = "octoguns-actions-3f08332a"
