kind = "DojoContract"
class_hash = "0x31a4d9c145241708d41b4699e0e70da082ef5a29f7c17ab66056ddef6707b54"
original_class_hash = "0x31a4d9c145241708d41b4699e0e70da082ef5a29f7c17ab66056ddef6707b54"
base_class_hash = "0x0"
abi = "manifests/mainnet/base/abis/contracts/octoguns-spawn-1acb0980.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-spawn"
systems = ["spawn"]
manifest_name = "octoguns-spawn-1acb0980"
