[package]
cairo-version = "=2.8.4"
name = "planetelo"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-rc.1" }
planetary_interface = { path = "../planetary_interface" }

[[target.starknet-contract]]
build-external-contracts = [
  "dojo::world::world_contract::world"
]

[profile.dev]
[profile.slot]
[profile.sepolia]