kind = "DojoModel"
class_hash = "0x46859e0aa4653b122074dc011896e0a3d7549e5194d9ee43a35cf6e9e87c3cb"
original_class_hash = "0x46859e0aa4653b122074dc011896e0a3d7549e5194d9ee43a35cf6e9e87c3cb"
abi = "manifests/dev/base/abis/models/octoguns-Player-5a4c6c7b.json"
tag = "octoguns-Player"
qualified_path = "octoguns::models::player::player"
manifest_name = "octoguns-Player-5a4c6c7b"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "player_name"
type = "ByteArray"
key = false

[[members]]
name = "games"
type = "Array<u32>"
key = false
