<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.10 /workspaces/Octoguns/client/static/3d/building-1.glb --root /3d/ --types --printwidth 120 --precision 2 --draco --transform --resolution 1024
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      BUILDING_11_1: THREE.Mesh
      BUILDING_11_2: THREE.Mesh
      BUILDING_11_3: THREE.Mesh
      BUILDING_11_4: THREE.Mesh
      BUILDING_11_5: THREE.Mesh
      BUILDING_11_6: THREE.Mesh
      BUILDING_11_7: THREE.Mesh
      BUILDING_11_8: THREE.Mesh
      BUILDING_11_9: THREE.Mesh
      BUILDING_11_10: THREE.Mesh
      BUILDING_11_11: THREE.Mesh
      BUILDING_11_12: THREE.Mesh
      BUILDING_11_13: THREE.Mesh
      BUILDING_11_14: THREE.Mesh
    }
    materials: {
      ['CUBE 1']: THREE.MeshStandardMaterial
      DOME: THREE.MeshStandardMaterial
      ['STRIP 2']: THREE.MeshStandardMaterial
      ['STRIP  1']: THREE.MeshStandardMaterial
      ['ARROW 2']: THREE.MeshStandardMaterial
      ['SMOOTH ARROW 2']: THREE.MeshStandardMaterial
      ['ARROW 1']: THREE.MeshStandardMaterial
      ['ARROW 3']: THREE.MeshStandardMaterial
      ['WINDOW 2']: THREE.MeshStandardMaterial
      ['SMOOTH ARROW 1']: THREE.MeshStandardMaterial
      ['WINDOW 1']: THREE.MeshStandardMaterial
      STATUE: THREE.MeshStandardMaterial
      ['CUBE 3']: THREE.MeshStandardMaterial
      ['BODY 2']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/3d/building-1-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_1.geometry}
        material={gltf.materials['CUBE 1']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_2.geometry}
        material={gltf.materials.DOME}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_3.geometry}
        material={gltf.materials['STRIP 2']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_4.geometry}
        material={gltf.materials['STRIP  1']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_5.geometry}
        material={gltf.materials['ARROW 2']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_6.geometry}
        material={gltf.materials['SMOOTH ARROW 2']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_7.geometry}
        material={gltf.materials['ARROW 1']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_8.geometry}
        material={gltf.materials['ARROW 3']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_9.geometry}
        material={gltf.materials['WINDOW 2']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_10.geometry}
        material={gltf.materials['SMOOTH ARROW 1']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_11.geometry}
        material={gltf.materials['WINDOW 1']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_12.geometry}
        material={gltf.materials.STATUE}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_13.geometry}
        material={gltf.materials['CUBE 3']}
      />
      <T.Mesh
        geometry={gltf.nodes.BUILDING_11_14.geometry}
        material={gltf.materials['BODY 2']}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
