<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.10 ./static/3d/container-transformed.glb -t --draco
-->

<script lang="ts">
  import * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useDraco, useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      mesh_0: THREE.Mesh
      mesh_0_1: THREE.Mesh
      mesh_0_2: THREE.Mesh
      mesh_0_3: THREE.Mesh
      mesh_0_4: THREE.Mesh
      mesh_0_5: THREE.Mesh
      mesh_0_6: THREE.Mesh
      mesh_0_7: THREE.Mesh
      mesh_0_8: THREE.Mesh
      mesh_0_9: THREE.Mesh
      mesh_0_10: THREE.Mesh
      mesh_0_11: THREE.Mesh
      mesh_0_12: THREE.Mesh
      mesh_0_13: THREE.Mesh
      mesh_0_14: THREE.Mesh
      mesh_1: THREE.Mesh
      mesh_1_1: THREE.Mesh
      mesh_2: THREE.Mesh
      mesh_2_1: THREE.Mesh
    }
    materials: {
      ['Material.007']: THREE.MeshPhysicalMaterial
      ['Material.008']: THREE.MeshPhysicalMaterial
      ['Material.011']: THREE.MeshStandardMaterial
      WING: THREE.MeshStandardMaterial
      ['ARC 2']: THREE.MeshStandardMaterial
      ['ARC 1']: THREE.MeshStandardMaterial
      ROMBO: THREE.MeshStandardMaterial
      BEAMS: THREE.MeshStandardMaterial
      ['CENTER TOP']: THREE.MeshStandardMaterial
      ['GLASS BORDER']: THREE.MeshPhysicalMaterial
      ['CENTER GLASS ']: THREE.MeshPhysicalMaterial
      ['Material.010']: THREE.MeshStandardMaterial
      ['Material.009']: THREE.MeshStandardMaterial
      ['Material.006']: THREE.MeshStandardMaterial
      ['Material.005']: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
    }
  }
  const dracoLoader = useDraco()

  const gltf = useGltf<GLTFResult>('/3d/container-transformed.glb', {
    dracoLoader,
  })
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation={[-Math.PI, 0, 0]}         side={THREE.FrontSide}
    >
      <T.Mesh
        geometry={gltf.nodes.mesh_0.geometry}
        material={gltf.materials['Material.007']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_1.geometry}
        material={gltf.materials['Material.008']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_2.geometry}
        material={gltf.materials['Material.011']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_3.geometry}
        material={gltf.materials.WING}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_4.geometry}
        material={gltf.materials['ARC 2']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_5.geometry}
        material={gltf.materials['ARC 1']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_6.geometry}
        material={gltf.materials.ROMBO}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_7.geometry}
        material={gltf.materials.BEAMS}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_8.geometry}
        material={gltf.materials['CENTER TOP']}
        side={THREE.FrontSide}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_9.geometry}
        material={gltf.materials['GLASS BORDER']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_10.geometry}
        material={gltf.materials['CENTER GLASS ']}
        side={THREE.FrontSide}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_11.geometry}
        material={gltf.materials['Material.010']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_12.geometry}
        material={gltf.materials['Material.010']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_13.geometry}
        material={gltf.materials['Material.009']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_0_14.geometry}
        material={gltf.materials['Material.006']}
        
      />
    </T.Group>
    <T.Group rotation={[0, Math.PI / 4, 0]} scale={1.2}>
      <T.Mesh
        geometry={gltf.nodes.mesh_1.geometry}
        material={gltf.materials['Material.005']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_1_1.geometry}
        material={gltf.materials['Material.001']}
      />
    </T.Group>
    <T.Group rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.2}>
      <T.Mesh
        geometry={gltf.nodes.mesh_2.geometry}
        material={gltf.materials['Material.005']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_2_1.geometry}
        material={gltf.materials['Material.001']}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
