<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 PISTOL_WALK_MAN_BLUE.glb --transform --types
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Armature|mixamo.com|Layer0'
  type GLTFResult = {
    nodes: {
      revolver_fire_btn_part: THREE.Mesh
      fig0019: THREE.SkinnedMesh
      mixamorigHips: THREE.Bone
    }
    materials: {
      lambert1: THREE.MeshStandardMaterial
      Material: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/3d/walking_man/PISTOL_WALK_MAN_BLUE-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={2}>
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="fig0019"
          geometry={gltf.nodes.fig0019.geometry}
          material={gltf.materials.Material}
          skeleton={gltf.nodes.fig0019.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
