<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 PISTOL_WALK_MAN_RED.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/3d/walking_man/PISTOL_WALK_MAN_RED-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="fig0019"
          geometry={gltf.nodes.fig0019.geometry}
          material={gltf.materials.Material}
          skeleton={gltf.nodes.fig0019.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
