kind = "DojoModel"
class_hash = "0x6f5dd520b74682ba2ec25cc02f73b38064c58d272e585a250c2edebdcb13f22"
original_class_hash = "0x6f5dd520b74682ba2ec25cc02f73b38064c58d272e585a250c2edebdcb13f22"
abi = "manifests/mainnet/base/abis/models/octoguns-Map-6508b277.json"
tag = "octoguns-Map"
qualified_path = "octoguns::models::map::map"
manifest_name = "octoguns-Map-6508b277"

[[members]]
name = "map_id"
type = "u32"
key = true

[[members]]
name = "grid1"
type = "u256"
key = false

[[members]]
name = "grid2"
type = "u256"
key = false

[[members]]
name = "grid3"
type = "u256"
key = false
