[package]
name = "planetary"
version = "0.1.0"
cairo-version = "2.7.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-rc.1" }
planetary_interface = { path = "../planetary_interface" }


[[target.starknet-contract]]
build-external-contracts = [
  "planetary_interface::systems::vulcan::salute",
  "dojo::world::world_contract::world"
]

#--------------------------
# Dojo profiles declaration
#
[profile.dev]
[profile.slot]
[profile.sepolia]