<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 container.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/container-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.mesh_0.geometry} material={gltf.materials['Material.007']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_1.geometry} material={gltf.materials['Material.008']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_2.geometry} material={gltf.materials['Material.011']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_3.geometry} material={gltf.materials.WING} />
      <T.Mesh geometry={gltf.nodes.mesh_0_4.geometry} material={gltf.materials['ARC 2']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_5.geometry} material={gltf.materials['ARC 1']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_6.geometry} material={gltf.materials.ROMBO} />
      <T.Mesh geometry={gltf.nodes.mesh_0_7.geometry} material={gltf.materials.BEAMS} />
      <T.Mesh geometry={gltf.nodes.mesh_0_8.geometry} material={gltf.materials['CENTER TOP']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_9.geometry} material={gltf.materials['GLASS BORDER']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_10.geometry} material={gltf.materials['CENTER GLASS ']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_11.geometry} material={gltf.materials['Material.010']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_12.geometry} material={gltf.materials['Material.010']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_13.geometry} material={gltf.materials['Material.009']} />
      <T.Mesh geometry={gltf.nodes.mesh_0_14.geometry} material={gltf.materials['Material.006']} />
    </T.Group>
    <T.Group rotation={[0, Math.PI / 4, 0]} scale={1.2}>
      <T.Mesh geometry={gltf.nodes.mesh_1.geometry} material={gltf.materials['Material.005']} />
      <T.Mesh geometry={gltf.nodes.mesh_1_1.geometry} material={gltf.materials['Material.001']} />
    </T.Group>
    <T.Group rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.2}>
      <T.Mesh geometry={gltf.nodes.mesh_2.geometry} material={gltf.materials['Material.005']} />
      <T.Mesh geometry={gltf.nodes.mesh_2_1.geometry} material={gltf.materials['Material.001']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
