kind = "DojoContract"
class_hash = "0x18605b41332326f7bded1b1f3f668a7d81850b01bbd77bd369e3efe0408aa8e"
original_class_hash = "0x18605b41332326f7bded1b1f3f668a7d81850b01bbd77bd369e3efe0408aa8e"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/octoguns-actions-3f08332a.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-actions"
systems = ["move"]
manifest_name = "octoguns-actions-3f08332a"
