kind = "DojoContract"
class_hash = "0x14e9f226786a43082deea7ffc3fbb308e932cdeffa597d93620c09c1cf71c8"
original_class_hash = "0x14e9f226786a43082deea7ffc3fbb308e932cdeffa597d93620c09c1cf71c8"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/octoguns-actions-3f08332a.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-actions"
systems = ["move"]
manifest_name = "octoguns-actions-3f08332a"
