kind = "DojoContract"
class_hash = "0x6aaf8c77a569341814403074f6467760f37e8154c8bba18eafa3895c9ddafc7"
original_class_hash = "0x6aaf8c77a569341814403074f6467760f37e8154c8bba18eafa3895c9ddafc7"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-actions-3f08332a.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-actions"
systems = ["move"]
manifest_name = "octoguns-actions-3f08332a"
